### ISSUE TITLE
Child combinator support like div > span

### ISSUE THREAD

**Issue by Grawl** [phloe/posthtml-match-helper#5]
Actual behaviour:

```js
console.log(matchHelper("div > span"))
>> { tag: "div > span" }
```

Expected behaviour:

```js
console.log(matchHelper("div > span"))
>> { tag: "div", content: [ { tag: 'span' } ] }
```

**Comment by phloe** [comment]
_As is_ the helper only supports shallow selectors (no child/adjacent sibling selectors) as I couldn't figure out how to implement it at the time :)

If the expected behaviour you list is correct it might not be so difficult to implement :)

**Comment by Grawl** [comment]
Its easy to implement but it will be useless because `node` will be `div` with `span` in `content[]`.

**Comment by phloe** [comment]
Then it's more an issue with posthtml's match object? That it doesn't support a way to express matching a node only when it's parent matches a certain match object?

**Comment by Grawl** [comment]
This feature looks like CSS’ `:has()`

**Comment by phloe** [comment]
Ok - so you're saying your initial listed actual behaviour wasn't what you actually meant?
Instead of `div > span` it should've been `div:has(> span)`?
So you still get the `div` node?

**Comment by Grawl** [comment]
Yes, I mean that `tree.match` works like `:has` when you provide `content`, so the following things are identical:

```js
tree.match({ tag: "div", content: [ { tag: 'span' } ] }, node => {})
```

```css
div:has(> span)
```

Each will target `div` not `span`

**Comment by phloe** [comment]
Ok - that means it's outside the scope of posthtml-match-helper :)

AFAICT the matcher argument that `tree.match` accepts doesn't support what you want at the moment - but you could go raise an issue in the posthtml repo :)

So I'm closing this issue for now.

**Comment by Grawl** [comment]
Maybe you will add `:has` support?
